// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: swapserverrpc/common.proto

package looprpc;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HopHintOrBuilder extends
      // @@protoc_insertion_point(interface_extends:looprpc.HopHint)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The public key of the node at the start of the channel.
     * </pre>
     *
     * <code>string node_id = 1;</code>
     * @return The nodeId.
     */
    java.lang.String getNodeId();
    /**
     * <pre>
     * The public key of the node at the start of the channel.
     * </pre>
     *
     * <code>string node_id = 1;</code>
     * @return The bytes for nodeId.
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();

    /**
     * <pre>
     * The unique identifier of the channel.
     * </pre>
     *
     * <code>uint64 chan_id = 2 [jstype = JS_STRING];</code>
     * @return The chanId.
     */
    long getChanId();

    /**
     * <pre>
     * The base fee of the channel denominated in millisatoshis.
     * </pre>
     *
     * <code>uint32 fee_base_msat = 3;</code>
     * @return The feeBaseMsat.
     */
    int getFeeBaseMsat();

    /**
     * <pre>
     *
     *The fee rate of the channel for sending one satoshi across it denominated in
     *millionths of a satoshi.
     * </pre>
     *
     * <code>uint32 fee_proportional_millionths = 4;</code>
     * @return The feeProportionalMillionths.
     */
    int getFeeProportionalMillionths();

    /**
     * <pre>
     * The time-lock delta of the channel.
     * </pre>
     *
     * <code>uint32 cltv_expiry_delta = 5;</code>
     * @return The cltvExpiryDelta.
     */
    int getCltvExpiryDelta();
  }
  /**
   * Protobuf type {@code looprpc.HopHint}
   */
  public static final class HopHint extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:looprpc.HopHint)
      HopHintOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HopHint.newBuilder() to construct.
    private HopHint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HopHint() {
      nodeId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HopHint();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return looprpc.Common.internal_static_looprpc_HopHint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return looprpc.Common.internal_static_looprpc_HopHint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              looprpc.Common.HopHint.class, looprpc.Common.HopHint.Builder.class);
    }

    public static final int NODE_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nodeId_ = "";
    /**
     * <pre>
     * The public key of the node at the start of the channel.
     * </pre>
     *
     * <code>string node_id = 1;</code>
     * @return The nodeId.
     */
    @java.lang.Override
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The public key of the node at the start of the channel.
     * </pre>
     *
     * <code>string node_id = 1;</code>
     * @return The bytes for nodeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHAN_ID_FIELD_NUMBER = 2;
    private long chanId_ = 0L;
    /**
     * <pre>
     * The unique identifier of the channel.
     * </pre>
     *
     * <code>uint64 chan_id = 2 [jstype = JS_STRING];</code>
     * @return The chanId.
     */
    @java.lang.Override
    public long getChanId() {
      return chanId_;
    }

    public static final int FEE_BASE_MSAT_FIELD_NUMBER = 3;
    private int feeBaseMsat_ = 0;
    /**
     * <pre>
     * The base fee of the channel denominated in millisatoshis.
     * </pre>
     *
     * <code>uint32 fee_base_msat = 3;</code>
     * @return The feeBaseMsat.
     */
    @java.lang.Override
    public int getFeeBaseMsat() {
      return feeBaseMsat_;
    }

    public static final int FEE_PROPORTIONAL_MILLIONTHS_FIELD_NUMBER = 4;
    private int feeProportionalMillionths_ = 0;
    /**
     * <pre>
     *
     *The fee rate of the channel for sending one satoshi across it denominated in
     *millionths of a satoshi.
     * </pre>
     *
     * <code>uint32 fee_proportional_millionths = 4;</code>
     * @return The feeProportionalMillionths.
     */
    @java.lang.Override
    public int getFeeProportionalMillionths() {
      return feeProportionalMillionths_;
    }

    public static final int CLTV_EXPIRY_DELTA_FIELD_NUMBER = 5;
    private int cltvExpiryDelta_ = 0;
    /**
     * <pre>
     * The time-lock delta of the channel.
     * </pre>
     *
     * <code>uint32 cltv_expiry_delta = 5;</code>
     * @return The cltvExpiryDelta.
     */
    @java.lang.Override
    public int getCltvExpiryDelta() {
      return cltvExpiryDelta_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeId_);
      }
      if (chanId_ != 0L) {
        output.writeUInt64(2, chanId_);
      }
      if (feeBaseMsat_ != 0) {
        output.writeUInt32(3, feeBaseMsat_);
      }
      if (feeProportionalMillionths_ != 0) {
        output.writeUInt32(4, feeProportionalMillionths_);
      }
      if (cltvExpiryDelta_ != 0) {
        output.writeUInt32(5, cltvExpiryDelta_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nodeId_);
      }
      if (chanId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, chanId_);
      }
      if (feeBaseMsat_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, feeBaseMsat_);
      }
      if (feeProportionalMillionths_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, feeProportionalMillionths_);
      }
      if (cltvExpiryDelta_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, cltvExpiryDelta_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof looprpc.Common.HopHint)) {
        return super.equals(obj);
      }
      looprpc.Common.HopHint other = (looprpc.Common.HopHint) obj;

      if (!getNodeId()
          .equals(other.getNodeId())) return false;
      if (getChanId()
          != other.getChanId()) return false;
      if (getFeeBaseMsat()
          != other.getFeeBaseMsat()) return false;
      if (getFeeProportionalMillionths()
          != other.getFeeProportionalMillionths()) return false;
      if (getCltvExpiryDelta()
          != other.getCltvExpiryDelta()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeId().hashCode();
      hash = (37 * hash) + CHAN_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getChanId());
      hash = (37 * hash) + FEE_BASE_MSAT_FIELD_NUMBER;
      hash = (53 * hash) + getFeeBaseMsat();
      hash = (37 * hash) + FEE_PROPORTIONAL_MILLIONTHS_FIELD_NUMBER;
      hash = (53 * hash) + getFeeProportionalMillionths();
      hash = (37 * hash) + CLTV_EXPIRY_DELTA_FIELD_NUMBER;
      hash = (53 * hash) + getCltvExpiryDelta();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static looprpc.Common.HopHint parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static looprpc.Common.HopHint parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static looprpc.Common.HopHint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static looprpc.Common.HopHint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static looprpc.Common.HopHint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static looprpc.Common.HopHint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static looprpc.Common.HopHint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static looprpc.Common.HopHint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static looprpc.Common.HopHint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static looprpc.Common.HopHint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static looprpc.Common.HopHint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static looprpc.Common.HopHint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(looprpc.Common.HopHint prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code looprpc.HopHint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:looprpc.HopHint)
        looprpc.Common.HopHintOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return looprpc.Common.internal_static_looprpc_HopHint_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return looprpc.Common.internal_static_looprpc_HopHint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                looprpc.Common.HopHint.class, looprpc.Common.HopHint.Builder.class);
      }

      // Construct using looprpc.Common.HopHint.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nodeId_ = "";
        chanId_ = 0L;
        feeBaseMsat_ = 0;
        feeProportionalMillionths_ = 0;
        cltvExpiryDelta_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return looprpc.Common.internal_static_looprpc_HopHint_descriptor;
      }

      @java.lang.Override
      public looprpc.Common.HopHint getDefaultInstanceForType() {
        return looprpc.Common.HopHint.getDefaultInstance();
      }

      @java.lang.Override
      public looprpc.Common.HopHint build() {
        looprpc.Common.HopHint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public looprpc.Common.HopHint buildPartial() {
        looprpc.Common.HopHint result = new looprpc.Common.HopHint(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(looprpc.Common.HopHint result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nodeId_ = nodeId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.chanId_ = chanId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.feeBaseMsat_ = feeBaseMsat_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.feeProportionalMillionths_ = feeProportionalMillionths_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.cltvExpiryDelta_ = cltvExpiryDelta_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof looprpc.Common.HopHint) {
          return mergeFrom((looprpc.Common.HopHint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(looprpc.Common.HopHint other) {
        if (other == looprpc.Common.HopHint.getDefaultInstance()) return this;
        if (!other.getNodeId().isEmpty()) {
          nodeId_ = other.nodeId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getChanId() != 0L) {
          setChanId(other.getChanId());
        }
        if (other.getFeeBaseMsat() != 0) {
          setFeeBaseMsat(other.getFeeBaseMsat());
        }
        if (other.getFeeProportionalMillionths() != 0) {
          setFeeProportionalMillionths(other.getFeeProportionalMillionths());
        }
        if (other.getCltvExpiryDelta() != 0) {
          setCltvExpiryDelta(other.getCltvExpiryDelta());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nodeId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                chanId_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                feeBaseMsat_ = input.readUInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                feeProportionalMillionths_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                cltvExpiryDelta_ = input.readUInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object nodeId_ = "";
      /**
       * <pre>
       * The public key of the node at the start of the channel.
       * </pre>
       *
       * <code>string node_id = 1;</code>
       * @return The nodeId.
       */
      public java.lang.String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The public key of the node at the start of the channel.
       * </pre>
       *
       * <code>string node_id = 1;</code>
       * @return The bytes for nodeId.
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        java.lang.Object ref = nodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The public key of the node at the start of the channel.
       * </pre>
       *
       * <code>string node_id = 1;</code>
       * @param value The nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nodeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The public key of the node at the start of the channel.
       * </pre>
       *
       * <code>string node_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeId() {
        nodeId_ = getDefaultInstance().getNodeId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The public key of the node at the start of the channel.
       * </pre>
       *
       * <code>string node_id = 1;</code>
       * @param value The bytes for nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nodeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private long chanId_ ;
      /**
       * <pre>
       * The unique identifier of the channel.
       * </pre>
       *
       * <code>uint64 chan_id = 2 [jstype = JS_STRING];</code>
       * @return The chanId.
       */
      @java.lang.Override
      public long getChanId() {
        return chanId_;
      }
      /**
       * <pre>
       * The unique identifier of the channel.
       * </pre>
       *
       * <code>uint64 chan_id = 2 [jstype = JS_STRING];</code>
       * @param value The chanId to set.
       * @return This builder for chaining.
       */
      public Builder setChanId(long value) {

        chanId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The unique identifier of the channel.
       * </pre>
       *
       * <code>uint64 chan_id = 2 [jstype = JS_STRING];</code>
       * @return This builder for chaining.
       */
      public Builder clearChanId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        chanId_ = 0L;
        onChanged();
        return this;
      }

      private int feeBaseMsat_ ;
      /**
       * <pre>
       * The base fee of the channel denominated in millisatoshis.
       * </pre>
       *
       * <code>uint32 fee_base_msat = 3;</code>
       * @return The feeBaseMsat.
       */
      @java.lang.Override
      public int getFeeBaseMsat() {
        return feeBaseMsat_;
      }
      /**
       * <pre>
       * The base fee of the channel denominated in millisatoshis.
       * </pre>
       *
       * <code>uint32 fee_base_msat = 3;</code>
       * @param value The feeBaseMsat to set.
       * @return This builder for chaining.
       */
      public Builder setFeeBaseMsat(int value) {

        feeBaseMsat_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The base fee of the channel denominated in millisatoshis.
       * </pre>
       *
       * <code>uint32 fee_base_msat = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFeeBaseMsat() {
        bitField0_ = (bitField0_ & ~0x00000004);
        feeBaseMsat_ = 0;
        onChanged();
        return this;
      }

      private int feeProportionalMillionths_ ;
      /**
       * <pre>
       *
       *The fee rate of the channel for sending one satoshi across it denominated in
       *millionths of a satoshi.
       * </pre>
       *
       * <code>uint32 fee_proportional_millionths = 4;</code>
       * @return The feeProportionalMillionths.
       */
      @java.lang.Override
      public int getFeeProportionalMillionths() {
        return feeProportionalMillionths_;
      }
      /**
       * <pre>
       *
       *The fee rate of the channel for sending one satoshi across it denominated in
       *millionths of a satoshi.
       * </pre>
       *
       * <code>uint32 fee_proportional_millionths = 4;</code>
       * @param value The feeProportionalMillionths to set.
       * @return This builder for chaining.
       */
      public Builder setFeeProportionalMillionths(int value) {

        feeProportionalMillionths_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *
       *The fee rate of the channel for sending one satoshi across it denominated in
       *millionths of a satoshi.
       * </pre>
       *
       * <code>uint32 fee_proportional_millionths = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFeeProportionalMillionths() {
        bitField0_ = (bitField0_ & ~0x00000008);
        feeProportionalMillionths_ = 0;
        onChanged();
        return this;
      }

      private int cltvExpiryDelta_ ;
      /**
       * <pre>
       * The time-lock delta of the channel.
       * </pre>
       *
       * <code>uint32 cltv_expiry_delta = 5;</code>
       * @return The cltvExpiryDelta.
       */
      @java.lang.Override
      public int getCltvExpiryDelta() {
        return cltvExpiryDelta_;
      }
      /**
       * <pre>
       * The time-lock delta of the channel.
       * </pre>
       *
       * <code>uint32 cltv_expiry_delta = 5;</code>
       * @param value The cltvExpiryDelta to set.
       * @return This builder for chaining.
       */
      public Builder setCltvExpiryDelta(int value) {

        cltvExpiryDelta_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The time-lock delta of the channel.
       * </pre>
       *
       * <code>uint32 cltv_expiry_delta = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCltvExpiryDelta() {
        bitField0_ = (bitField0_ & ~0x00000010);
        cltvExpiryDelta_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:looprpc.HopHint)
    }

    // @@protoc_insertion_point(class_scope:looprpc.HopHint)
    private static final looprpc.Common.HopHint DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new looprpc.Common.HopHint();
    }

    public static looprpc.Common.HopHint getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HopHint>
        PARSER = new com.google.protobuf.AbstractParser<HopHint>() {
      @java.lang.Override
      public HopHint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HopHint> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HopHint> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public looprpc.Common.HopHint getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RouteHintOrBuilder extends
      // @@protoc_insertion_point(interface_extends:looprpc.RouteHint)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *
     *A list of hop hints that when chained together can assist in reaching a
     *specific destination.
     * </pre>
     *
     * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
     */
    java.util.List<looprpc.Common.HopHint> 
        getHopHintsList();
    /**
     * <pre>
     *
     *A list of hop hints that when chained together can assist in reaching a
     *specific destination.
     * </pre>
     *
     * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
     */
    looprpc.Common.HopHint getHopHints(int index);
    /**
     * <pre>
     *
     *A list of hop hints that when chained together can assist in reaching a
     *specific destination.
     * </pre>
     *
     * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
     */
    int getHopHintsCount();
    /**
     * <pre>
     *
     *A list of hop hints that when chained together can assist in reaching a
     *specific destination.
     * </pre>
     *
     * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
     */
    java.util.List<? extends looprpc.Common.HopHintOrBuilder> 
        getHopHintsOrBuilderList();
    /**
     * <pre>
     *
     *A list of hop hints that when chained together can assist in reaching a
     *specific destination.
     * </pre>
     *
     * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
     */
    looprpc.Common.HopHintOrBuilder getHopHintsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code looprpc.RouteHint}
   */
  public static final class RouteHint extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:looprpc.RouteHint)
      RouteHintOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RouteHint.newBuilder() to construct.
    private RouteHint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RouteHint() {
      hopHints_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RouteHint();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return looprpc.Common.internal_static_looprpc_RouteHint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return looprpc.Common.internal_static_looprpc_RouteHint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              looprpc.Common.RouteHint.class, looprpc.Common.RouteHint.Builder.class);
    }

    public static final int HOP_HINTS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<looprpc.Common.HopHint> hopHints_;
    /**
     * <pre>
     *
     *A list of hop hints that when chained together can assist in reaching a
     *specific destination.
     * </pre>
     *
     * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
     */
    @java.lang.Override
    public java.util.List<looprpc.Common.HopHint> getHopHintsList() {
      return hopHints_;
    }
    /**
     * <pre>
     *
     *A list of hop hints that when chained together can assist in reaching a
     *specific destination.
     * </pre>
     *
     * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends looprpc.Common.HopHintOrBuilder> 
        getHopHintsOrBuilderList() {
      return hopHints_;
    }
    /**
     * <pre>
     *
     *A list of hop hints that when chained together can assist in reaching a
     *specific destination.
     * </pre>
     *
     * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
     */
    @java.lang.Override
    public int getHopHintsCount() {
      return hopHints_.size();
    }
    /**
     * <pre>
     *
     *A list of hop hints that when chained together can assist in reaching a
     *specific destination.
     * </pre>
     *
     * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
     */
    @java.lang.Override
    public looprpc.Common.HopHint getHopHints(int index) {
      return hopHints_.get(index);
    }
    /**
     * <pre>
     *
     *A list of hop hints that when chained together can assist in reaching a
     *specific destination.
     * </pre>
     *
     * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
     */
    @java.lang.Override
    public looprpc.Common.HopHintOrBuilder getHopHintsOrBuilder(
        int index) {
      return hopHints_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < hopHints_.size(); i++) {
        output.writeMessage(1, hopHints_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < hopHints_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, hopHints_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof looprpc.Common.RouteHint)) {
        return super.equals(obj);
      }
      looprpc.Common.RouteHint other = (looprpc.Common.RouteHint) obj;

      if (!getHopHintsList()
          .equals(other.getHopHintsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getHopHintsCount() > 0) {
        hash = (37 * hash) + HOP_HINTS_FIELD_NUMBER;
        hash = (53 * hash) + getHopHintsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static looprpc.Common.RouteHint parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static looprpc.Common.RouteHint parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static looprpc.Common.RouteHint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static looprpc.Common.RouteHint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static looprpc.Common.RouteHint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static looprpc.Common.RouteHint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static looprpc.Common.RouteHint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static looprpc.Common.RouteHint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static looprpc.Common.RouteHint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static looprpc.Common.RouteHint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static looprpc.Common.RouteHint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static looprpc.Common.RouteHint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(looprpc.Common.RouteHint prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code looprpc.RouteHint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:looprpc.RouteHint)
        looprpc.Common.RouteHintOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return looprpc.Common.internal_static_looprpc_RouteHint_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return looprpc.Common.internal_static_looprpc_RouteHint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                looprpc.Common.RouteHint.class, looprpc.Common.RouteHint.Builder.class);
      }

      // Construct using looprpc.Common.RouteHint.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (hopHintsBuilder_ == null) {
          hopHints_ = java.util.Collections.emptyList();
        } else {
          hopHints_ = null;
          hopHintsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return looprpc.Common.internal_static_looprpc_RouteHint_descriptor;
      }

      @java.lang.Override
      public looprpc.Common.RouteHint getDefaultInstanceForType() {
        return looprpc.Common.RouteHint.getDefaultInstance();
      }

      @java.lang.Override
      public looprpc.Common.RouteHint build() {
        looprpc.Common.RouteHint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public looprpc.Common.RouteHint buildPartial() {
        looprpc.Common.RouteHint result = new looprpc.Common.RouteHint(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(looprpc.Common.RouteHint result) {
        if (hopHintsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            hopHints_ = java.util.Collections.unmodifiableList(hopHints_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.hopHints_ = hopHints_;
        } else {
          result.hopHints_ = hopHintsBuilder_.build();
        }
      }

      private void buildPartial0(looprpc.Common.RouteHint result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof looprpc.Common.RouteHint) {
          return mergeFrom((looprpc.Common.RouteHint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(looprpc.Common.RouteHint other) {
        if (other == looprpc.Common.RouteHint.getDefaultInstance()) return this;
        if (hopHintsBuilder_ == null) {
          if (!other.hopHints_.isEmpty()) {
            if (hopHints_.isEmpty()) {
              hopHints_ = other.hopHints_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHopHintsIsMutable();
              hopHints_.addAll(other.hopHints_);
            }
            onChanged();
          }
        } else {
          if (!other.hopHints_.isEmpty()) {
            if (hopHintsBuilder_.isEmpty()) {
              hopHintsBuilder_.dispose();
              hopHintsBuilder_ = null;
              hopHints_ = other.hopHints_;
              bitField0_ = (bitField0_ & ~0x00000001);
              hopHintsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHopHintsFieldBuilder() : null;
            } else {
              hopHintsBuilder_.addAllMessages(other.hopHints_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                looprpc.Common.HopHint m =
                    input.readMessage(
                        looprpc.Common.HopHint.parser(),
                        extensionRegistry);
                if (hopHintsBuilder_ == null) {
                  ensureHopHintsIsMutable();
                  hopHints_.add(m);
                } else {
                  hopHintsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<looprpc.Common.HopHint> hopHints_ =
        java.util.Collections.emptyList();
      private void ensureHopHintsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          hopHints_ = new java.util.ArrayList<looprpc.Common.HopHint>(hopHints_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          looprpc.Common.HopHint, looprpc.Common.HopHint.Builder, looprpc.Common.HopHintOrBuilder> hopHintsBuilder_;

      /**
       * <pre>
       *
       *A list of hop hints that when chained together can assist in reaching a
       *specific destination.
       * </pre>
       *
       * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
       */
      public java.util.List<looprpc.Common.HopHint> getHopHintsList() {
        if (hopHintsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(hopHints_);
        } else {
          return hopHintsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *
       *A list of hop hints that when chained together can assist in reaching a
       *specific destination.
       * </pre>
       *
       * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
       */
      public int getHopHintsCount() {
        if (hopHintsBuilder_ == null) {
          return hopHints_.size();
        } else {
          return hopHintsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *
       *A list of hop hints that when chained together can assist in reaching a
       *specific destination.
       * </pre>
       *
       * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
       */
      public looprpc.Common.HopHint getHopHints(int index) {
        if (hopHintsBuilder_ == null) {
          return hopHints_.get(index);
        } else {
          return hopHintsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *
       *A list of hop hints that when chained together can assist in reaching a
       *specific destination.
       * </pre>
       *
       * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
       */
      public Builder setHopHints(
          int index, looprpc.Common.HopHint value) {
        if (hopHintsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHopHintsIsMutable();
          hopHints_.set(index, value);
          onChanged();
        } else {
          hopHintsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *
       *A list of hop hints that when chained together can assist in reaching a
       *specific destination.
       * </pre>
       *
       * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
       */
      public Builder setHopHints(
          int index, looprpc.Common.HopHint.Builder builderForValue) {
        if (hopHintsBuilder_ == null) {
          ensureHopHintsIsMutable();
          hopHints_.set(index, builderForValue.build());
          onChanged();
        } else {
          hopHintsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *
       *A list of hop hints that when chained together can assist in reaching a
       *specific destination.
       * </pre>
       *
       * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
       */
      public Builder addHopHints(looprpc.Common.HopHint value) {
        if (hopHintsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHopHintsIsMutable();
          hopHints_.add(value);
          onChanged();
        } else {
          hopHintsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *
       *A list of hop hints that when chained together can assist in reaching a
       *specific destination.
       * </pre>
       *
       * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
       */
      public Builder addHopHints(
          int index, looprpc.Common.HopHint value) {
        if (hopHintsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHopHintsIsMutable();
          hopHints_.add(index, value);
          onChanged();
        } else {
          hopHintsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *
       *A list of hop hints that when chained together can assist in reaching a
       *specific destination.
       * </pre>
       *
       * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
       */
      public Builder addHopHints(
          looprpc.Common.HopHint.Builder builderForValue) {
        if (hopHintsBuilder_ == null) {
          ensureHopHintsIsMutable();
          hopHints_.add(builderForValue.build());
          onChanged();
        } else {
          hopHintsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *
       *A list of hop hints that when chained together can assist in reaching a
       *specific destination.
       * </pre>
       *
       * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
       */
      public Builder addHopHints(
          int index, looprpc.Common.HopHint.Builder builderForValue) {
        if (hopHintsBuilder_ == null) {
          ensureHopHintsIsMutable();
          hopHints_.add(index, builderForValue.build());
          onChanged();
        } else {
          hopHintsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *
       *A list of hop hints that when chained together can assist in reaching a
       *specific destination.
       * </pre>
       *
       * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
       */
      public Builder addAllHopHints(
          java.lang.Iterable<? extends looprpc.Common.HopHint> values) {
        if (hopHintsBuilder_ == null) {
          ensureHopHintsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, hopHints_);
          onChanged();
        } else {
          hopHintsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *
       *A list of hop hints that when chained together can assist in reaching a
       *specific destination.
       * </pre>
       *
       * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
       */
      public Builder clearHopHints() {
        if (hopHintsBuilder_ == null) {
          hopHints_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          hopHintsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *
       *A list of hop hints that when chained together can assist in reaching a
       *specific destination.
       * </pre>
       *
       * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
       */
      public Builder removeHopHints(int index) {
        if (hopHintsBuilder_ == null) {
          ensureHopHintsIsMutable();
          hopHints_.remove(index);
          onChanged();
        } else {
          hopHintsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *
       *A list of hop hints that when chained together can assist in reaching a
       *specific destination.
       * </pre>
       *
       * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
       */
      public looprpc.Common.HopHint.Builder getHopHintsBuilder(
          int index) {
        return getHopHintsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *
       *A list of hop hints that when chained together can assist in reaching a
       *specific destination.
       * </pre>
       *
       * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
       */
      public looprpc.Common.HopHintOrBuilder getHopHintsOrBuilder(
          int index) {
        if (hopHintsBuilder_ == null) {
          return hopHints_.get(index);  } else {
          return hopHintsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *
       *A list of hop hints that when chained together can assist in reaching a
       *specific destination.
       * </pre>
       *
       * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
       */
      public java.util.List<? extends looprpc.Common.HopHintOrBuilder> 
           getHopHintsOrBuilderList() {
        if (hopHintsBuilder_ != null) {
          return hopHintsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(hopHints_);
        }
      }
      /**
       * <pre>
       *
       *A list of hop hints that when chained together can assist in reaching a
       *specific destination.
       * </pre>
       *
       * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
       */
      public looprpc.Common.HopHint.Builder addHopHintsBuilder() {
        return getHopHintsFieldBuilder().addBuilder(
            looprpc.Common.HopHint.getDefaultInstance());
      }
      /**
       * <pre>
       *
       *A list of hop hints that when chained together can assist in reaching a
       *specific destination.
       * </pre>
       *
       * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
       */
      public looprpc.Common.HopHint.Builder addHopHintsBuilder(
          int index) {
        return getHopHintsFieldBuilder().addBuilder(
            index, looprpc.Common.HopHint.getDefaultInstance());
      }
      /**
       * <pre>
       *
       *A list of hop hints that when chained together can assist in reaching a
       *specific destination.
       * </pre>
       *
       * <code>repeated .looprpc.HopHint hop_hints = 1;</code>
       */
      public java.util.List<looprpc.Common.HopHint.Builder> 
           getHopHintsBuilderList() {
        return getHopHintsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          looprpc.Common.HopHint, looprpc.Common.HopHint.Builder, looprpc.Common.HopHintOrBuilder> 
          getHopHintsFieldBuilder() {
        if (hopHintsBuilder_ == null) {
          hopHintsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              looprpc.Common.HopHint, looprpc.Common.HopHint.Builder, looprpc.Common.HopHintOrBuilder>(
                  hopHints_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          hopHints_ = null;
        }
        return hopHintsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:looprpc.RouteHint)
    }

    // @@protoc_insertion_point(class_scope:looprpc.RouteHint)
    private static final looprpc.Common.RouteHint DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new looprpc.Common.RouteHint();
    }

    public static looprpc.Common.RouteHint getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RouteHint>
        PARSER = new com.google.protobuf.AbstractParser<RouteHint>() {
      @java.lang.Override
      public RouteHint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RouteHint> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RouteHint> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public looprpc.Common.RouteHint getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_looprpc_HopHint_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_looprpc_HopHint_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_looprpc_RouteHint_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_looprpc_RouteHint_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032swapserverrpc/common.proto\022\007looprpc\"\206\001" +
      "\n\007HopHint\022\017\n\007node_id\030\001 \001(\t\022\023\n\007chan_id\030\002 " +
      "\001(\004B\0020\001\022\025\n\rfee_base_msat\030\003 \001(\r\022#\n\033fee_pr" +
      "oportional_millionths\030\004 \001(\r\022\031\n\021cltv_expi" +
      "ry_delta\030\005 \001(\r\"0\n\tRouteHint\022#\n\thop_hints" +
      "\030\001 \003(\0132\020.looprpc.HopHintB-Z+github.com/l" +
      "ightninglabs/loop/swapserverrpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_looprpc_HopHint_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_looprpc_HopHint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_looprpc_HopHint_descriptor,
        new java.lang.String[] { "NodeId", "ChanId", "FeeBaseMsat", "FeeProportionalMillionths", "CltvExpiryDelta", });
    internal_static_looprpc_RouteHint_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_looprpc_RouteHint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_looprpc_RouteHint_descriptor,
        new java.lang.String[] { "HopHints", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
