// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stateservice.proto

package lnrpc;

public final class Stateservice {
  private Stateservice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code lnrpc.WalletState}
   */
  public enum WalletState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * NON_EXISTING means that the wallet has not yet been initialized.
     * </pre>
     *
     * <code>NON_EXISTING = 0;</code>
     */
    NON_EXISTING(0),
    /**
     * <pre>
     * LOCKED means that the wallet is locked and requires a password to unlock.
     * </pre>
     *
     * <code>LOCKED = 1;</code>
     */
    LOCKED(1),
    /**
     * <pre>
     * UNLOCKED means that the wallet was unlocked successfully, but RPC server
     * isn't ready.
     * </pre>
     *
     * <code>UNLOCKED = 2;</code>
     */
    UNLOCKED(2),
    /**
     * <pre>
     * RPC_ACTIVE means that the lnd server is active but not fully ready for
     * calls.
     * </pre>
     *
     * <code>RPC_ACTIVE = 3;</code>
     */
    RPC_ACTIVE(3),
    /**
     * <pre>
     * SERVER_ACTIVE means that the lnd server is ready to accept calls.
     * </pre>
     *
     * <code>SERVER_ACTIVE = 4;</code>
     */
    SERVER_ACTIVE(4),
    /**
     * <pre>
     * WAITING_TO_START means that node is waiting to become the leader in a
     * cluster and is not started yet.
     * </pre>
     *
     * <code>WAITING_TO_START = 255;</code>
     */
    WAITING_TO_START(255),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * NON_EXISTING means that the wallet has not yet been initialized.
     * </pre>
     *
     * <code>NON_EXISTING = 0;</code>
     */
    public static final int NON_EXISTING_VALUE = 0;
    /**
     * <pre>
     * LOCKED means that the wallet is locked and requires a password to unlock.
     * </pre>
     *
     * <code>LOCKED = 1;</code>
     */
    public static final int LOCKED_VALUE = 1;
    /**
     * <pre>
     * UNLOCKED means that the wallet was unlocked successfully, but RPC server
     * isn't ready.
     * </pre>
     *
     * <code>UNLOCKED = 2;</code>
     */
    public static final int UNLOCKED_VALUE = 2;
    /**
     * <pre>
     * RPC_ACTIVE means that the lnd server is active but not fully ready for
     * calls.
     * </pre>
     *
     * <code>RPC_ACTIVE = 3;</code>
     */
    public static final int RPC_ACTIVE_VALUE = 3;
    /**
     * <pre>
     * SERVER_ACTIVE means that the lnd server is ready to accept calls.
     * </pre>
     *
     * <code>SERVER_ACTIVE = 4;</code>
     */
    public static final int SERVER_ACTIVE_VALUE = 4;
    /**
     * <pre>
     * WAITING_TO_START means that node is waiting to become the leader in a
     * cluster and is not started yet.
     * </pre>
     *
     * <code>WAITING_TO_START = 255;</code>
     */
    public static final int WAITING_TO_START_VALUE = 255;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static WalletState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static WalletState forNumber(int value) {
      switch (value) {
        case 0: return NON_EXISTING;
        case 1: return LOCKED;
        case 2: return UNLOCKED;
        case 3: return RPC_ACTIVE;
        case 4: return SERVER_ACTIVE;
        case 255: return WAITING_TO_START;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<WalletState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        WalletState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<WalletState>() {
            public WalletState findValueByNumber(int number) {
              return WalletState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return lnrpc.Stateservice.getDescriptor().getEnumTypes().get(0);
    }

    private static final WalletState[] VALUES = values();

    public static WalletState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private WalletState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:lnrpc.WalletState)
  }

  public interface SubscribeStateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lnrpc.SubscribeStateRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code lnrpc.SubscribeStateRequest}
   */
  public static final class SubscribeStateRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lnrpc.SubscribeStateRequest)
      SubscribeStateRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubscribeStateRequest.newBuilder() to construct.
    private SubscribeStateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubscribeStateRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SubscribeStateRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lnrpc.Stateservice.internal_static_lnrpc_SubscribeStateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lnrpc.Stateservice.internal_static_lnrpc_SubscribeStateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lnrpc.Stateservice.SubscribeStateRequest.class, lnrpc.Stateservice.SubscribeStateRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lnrpc.Stateservice.SubscribeStateRequest)) {
        return super.equals(obj);
      }
      lnrpc.Stateservice.SubscribeStateRequest other = (lnrpc.Stateservice.SubscribeStateRequest) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lnrpc.Stateservice.SubscribeStateRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lnrpc.Stateservice.SubscribeStateRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lnrpc.Stateservice.SubscribeStateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lnrpc.Stateservice.SubscribeStateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lnrpc.Stateservice.SubscribeStateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lnrpc.Stateservice.SubscribeStateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lnrpc.Stateservice.SubscribeStateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static lnrpc.Stateservice.SubscribeStateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lnrpc.Stateservice.SubscribeStateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lnrpc.Stateservice.SubscribeStateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lnrpc.Stateservice.SubscribeStateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static lnrpc.Stateservice.SubscribeStateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lnrpc.Stateservice.SubscribeStateRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lnrpc.SubscribeStateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lnrpc.SubscribeStateRequest)
        lnrpc.Stateservice.SubscribeStateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lnrpc.Stateservice.internal_static_lnrpc_SubscribeStateRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lnrpc.Stateservice.internal_static_lnrpc_SubscribeStateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lnrpc.Stateservice.SubscribeStateRequest.class, lnrpc.Stateservice.SubscribeStateRequest.Builder.class);
      }

      // Construct using lnrpc.Stateservice.SubscribeStateRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lnrpc.Stateservice.internal_static_lnrpc_SubscribeStateRequest_descriptor;
      }

      @java.lang.Override
      public lnrpc.Stateservice.SubscribeStateRequest getDefaultInstanceForType() {
        return lnrpc.Stateservice.SubscribeStateRequest.getDefaultInstance();
      }

      @java.lang.Override
      public lnrpc.Stateservice.SubscribeStateRequest build() {
        lnrpc.Stateservice.SubscribeStateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lnrpc.Stateservice.SubscribeStateRequest buildPartial() {
        lnrpc.Stateservice.SubscribeStateRequest result = new lnrpc.Stateservice.SubscribeStateRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lnrpc.Stateservice.SubscribeStateRequest) {
          return mergeFrom((lnrpc.Stateservice.SubscribeStateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lnrpc.Stateservice.SubscribeStateRequest other) {
        if (other == lnrpc.Stateservice.SubscribeStateRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lnrpc.SubscribeStateRequest)
    }

    // @@protoc_insertion_point(class_scope:lnrpc.SubscribeStateRequest)
    private static final lnrpc.Stateservice.SubscribeStateRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lnrpc.Stateservice.SubscribeStateRequest();
    }

    public static lnrpc.Stateservice.SubscribeStateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubscribeStateRequest>
        PARSER = new com.google.protobuf.AbstractParser<SubscribeStateRequest>() {
      @java.lang.Override
      public SubscribeStateRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SubscribeStateRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubscribeStateRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lnrpc.Stateservice.SubscribeStateRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SubscribeStateResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lnrpc.SubscribeStateResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.lnrpc.WalletState state = 1;</code>
     * @return The enum numeric value on the wire for state.
     */
    int getStateValue();
    /**
     * <code>.lnrpc.WalletState state = 1;</code>
     * @return The state.
     */
    lnrpc.Stateservice.WalletState getState();
  }
  /**
   * Protobuf type {@code lnrpc.SubscribeStateResponse}
   */
  public static final class SubscribeStateResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lnrpc.SubscribeStateResponse)
      SubscribeStateResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubscribeStateResponse.newBuilder() to construct.
    private SubscribeStateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubscribeStateResponse() {
      state_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SubscribeStateResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lnrpc.Stateservice.internal_static_lnrpc_SubscribeStateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lnrpc.Stateservice.internal_static_lnrpc_SubscribeStateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lnrpc.Stateservice.SubscribeStateResponse.class, lnrpc.Stateservice.SubscribeStateResponse.Builder.class);
    }

    public static final int STATE_FIELD_NUMBER = 1;
    private int state_ = 0;
    /**
     * <code>.lnrpc.WalletState state = 1;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <code>.lnrpc.WalletState state = 1;</code>
     * @return The state.
     */
    @java.lang.Override public lnrpc.Stateservice.WalletState getState() {
      lnrpc.Stateservice.WalletState result = lnrpc.Stateservice.WalletState.forNumber(state_);
      return result == null ? lnrpc.Stateservice.WalletState.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (state_ != lnrpc.Stateservice.WalletState.NON_EXISTING.getNumber()) {
        output.writeEnum(1, state_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (state_ != lnrpc.Stateservice.WalletState.NON_EXISTING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, state_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lnrpc.Stateservice.SubscribeStateResponse)) {
        return super.equals(obj);
      }
      lnrpc.Stateservice.SubscribeStateResponse other = (lnrpc.Stateservice.SubscribeStateResponse) obj;

      if (state_ != other.state_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lnrpc.Stateservice.SubscribeStateResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lnrpc.Stateservice.SubscribeStateResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lnrpc.Stateservice.SubscribeStateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lnrpc.Stateservice.SubscribeStateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lnrpc.Stateservice.SubscribeStateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lnrpc.Stateservice.SubscribeStateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lnrpc.Stateservice.SubscribeStateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static lnrpc.Stateservice.SubscribeStateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lnrpc.Stateservice.SubscribeStateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lnrpc.Stateservice.SubscribeStateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lnrpc.Stateservice.SubscribeStateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static lnrpc.Stateservice.SubscribeStateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lnrpc.Stateservice.SubscribeStateResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lnrpc.SubscribeStateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lnrpc.SubscribeStateResponse)
        lnrpc.Stateservice.SubscribeStateResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lnrpc.Stateservice.internal_static_lnrpc_SubscribeStateResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lnrpc.Stateservice.internal_static_lnrpc_SubscribeStateResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lnrpc.Stateservice.SubscribeStateResponse.class, lnrpc.Stateservice.SubscribeStateResponse.Builder.class);
      }

      // Construct using lnrpc.Stateservice.SubscribeStateResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        state_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lnrpc.Stateservice.internal_static_lnrpc_SubscribeStateResponse_descriptor;
      }

      @java.lang.Override
      public lnrpc.Stateservice.SubscribeStateResponse getDefaultInstanceForType() {
        return lnrpc.Stateservice.SubscribeStateResponse.getDefaultInstance();
      }

      @java.lang.Override
      public lnrpc.Stateservice.SubscribeStateResponse build() {
        lnrpc.Stateservice.SubscribeStateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lnrpc.Stateservice.SubscribeStateResponse buildPartial() {
        lnrpc.Stateservice.SubscribeStateResponse result = new lnrpc.Stateservice.SubscribeStateResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lnrpc.Stateservice.SubscribeStateResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.state_ = state_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lnrpc.Stateservice.SubscribeStateResponse) {
          return mergeFrom((lnrpc.Stateservice.SubscribeStateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lnrpc.Stateservice.SubscribeStateResponse other) {
        if (other == lnrpc.Stateservice.SubscribeStateResponse.getDefaultInstance()) return this;
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                state_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int state_ = 0;
      /**
       * <code>.lnrpc.WalletState state = 1;</code>
       * @return The enum numeric value on the wire for state.
       */
      @java.lang.Override public int getStateValue() {
        return state_;
      }
      /**
       * <code>.lnrpc.WalletState state = 1;</code>
       * @param value The enum numeric value on the wire for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateValue(int value) {
        state_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.lnrpc.WalletState state = 1;</code>
       * @return The state.
       */
      @java.lang.Override
      public lnrpc.Stateservice.WalletState getState() {
        lnrpc.Stateservice.WalletState result = lnrpc.Stateservice.WalletState.forNumber(state_);
        return result == null ? lnrpc.Stateservice.WalletState.UNRECOGNIZED : result;
      }
      /**
       * <code>.lnrpc.WalletState state = 1;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(lnrpc.Stateservice.WalletState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.lnrpc.WalletState state = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lnrpc.SubscribeStateResponse)
    }

    // @@protoc_insertion_point(class_scope:lnrpc.SubscribeStateResponse)
    private static final lnrpc.Stateservice.SubscribeStateResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lnrpc.Stateservice.SubscribeStateResponse();
    }

    public static lnrpc.Stateservice.SubscribeStateResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubscribeStateResponse>
        PARSER = new com.google.protobuf.AbstractParser<SubscribeStateResponse>() {
      @java.lang.Override
      public SubscribeStateResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SubscribeStateResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubscribeStateResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lnrpc.Stateservice.SubscribeStateResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetStateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lnrpc.GetStateRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code lnrpc.GetStateRequest}
   */
  public static final class GetStateRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lnrpc.GetStateRequest)
      GetStateRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetStateRequest.newBuilder() to construct.
    private GetStateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetStateRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetStateRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lnrpc.Stateservice.internal_static_lnrpc_GetStateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lnrpc.Stateservice.internal_static_lnrpc_GetStateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lnrpc.Stateservice.GetStateRequest.class, lnrpc.Stateservice.GetStateRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lnrpc.Stateservice.GetStateRequest)) {
        return super.equals(obj);
      }
      lnrpc.Stateservice.GetStateRequest other = (lnrpc.Stateservice.GetStateRequest) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lnrpc.Stateservice.GetStateRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lnrpc.Stateservice.GetStateRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lnrpc.Stateservice.GetStateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lnrpc.Stateservice.GetStateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lnrpc.Stateservice.GetStateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lnrpc.Stateservice.GetStateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lnrpc.Stateservice.GetStateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static lnrpc.Stateservice.GetStateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lnrpc.Stateservice.GetStateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lnrpc.Stateservice.GetStateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lnrpc.Stateservice.GetStateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static lnrpc.Stateservice.GetStateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lnrpc.Stateservice.GetStateRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lnrpc.GetStateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lnrpc.GetStateRequest)
        lnrpc.Stateservice.GetStateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lnrpc.Stateservice.internal_static_lnrpc_GetStateRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lnrpc.Stateservice.internal_static_lnrpc_GetStateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lnrpc.Stateservice.GetStateRequest.class, lnrpc.Stateservice.GetStateRequest.Builder.class);
      }

      // Construct using lnrpc.Stateservice.GetStateRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lnrpc.Stateservice.internal_static_lnrpc_GetStateRequest_descriptor;
      }

      @java.lang.Override
      public lnrpc.Stateservice.GetStateRequest getDefaultInstanceForType() {
        return lnrpc.Stateservice.GetStateRequest.getDefaultInstance();
      }

      @java.lang.Override
      public lnrpc.Stateservice.GetStateRequest build() {
        lnrpc.Stateservice.GetStateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lnrpc.Stateservice.GetStateRequest buildPartial() {
        lnrpc.Stateservice.GetStateRequest result = new lnrpc.Stateservice.GetStateRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lnrpc.Stateservice.GetStateRequest) {
          return mergeFrom((lnrpc.Stateservice.GetStateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lnrpc.Stateservice.GetStateRequest other) {
        if (other == lnrpc.Stateservice.GetStateRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lnrpc.GetStateRequest)
    }

    // @@protoc_insertion_point(class_scope:lnrpc.GetStateRequest)
    private static final lnrpc.Stateservice.GetStateRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lnrpc.Stateservice.GetStateRequest();
    }

    public static lnrpc.Stateservice.GetStateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetStateRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetStateRequest>() {
      @java.lang.Override
      public GetStateRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetStateRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetStateRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lnrpc.Stateservice.GetStateRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetStateResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lnrpc.GetStateResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.lnrpc.WalletState state = 1;</code>
     * @return The enum numeric value on the wire for state.
     */
    int getStateValue();
    /**
     * <code>.lnrpc.WalletState state = 1;</code>
     * @return The state.
     */
    lnrpc.Stateservice.WalletState getState();
  }
  /**
   * Protobuf type {@code lnrpc.GetStateResponse}
   */
  public static final class GetStateResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lnrpc.GetStateResponse)
      GetStateResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetStateResponse.newBuilder() to construct.
    private GetStateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetStateResponse() {
      state_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetStateResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lnrpc.Stateservice.internal_static_lnrpc_GetStateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lnrpc.Stateservice.internal_static_lnrpc_GetStateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lnrpc.Stateservice.GetStateResponse.class, lnrpc.Stateservice.GetStateResponse.Builder.class);
    }

    public static final int STATE_FIELD_NUMBER = 1;
    private int state_ = 0;
    /**
     * <code>.lnrpc.WalletState state = 1;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <code>.lnrpc.WalletState state = 1;</code>
     * @return The state.
     */
    @java.lang.Override public lnrpc.Stateservice.WalletState getState() {
      lnrpc.Stateservice.WalletState result = lnrpc.Stateservice.WalletState.forNumber(state_);
      return result == null ? lnrpc.Stateservice.WalletState.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (state_ != lnrpc.Stateservice.WalletState.NON_EXISTING.getNumber()) {
        output.writeEnum(1, state_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (state_ != lnrpc.Stateservice.WalletState.NON_EXISTING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, state_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lnrpc.Stateservice.GetStateResponse)) {
        return super.equals(obj);
      }
      lnrpc.Stateservice.GetStateResponse other = (lnrpc.Stateservice.GetStateResponse) obj;

      if (state_ != other.state_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lnrpc.Stateservice.GetStateResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lnrpc.Stateservice.GetStateResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lnrpc.Stateservice.GetStateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lnrpc.Stateservice.GetStateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lnrpc.Stateservice.GetStateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lnrpc.Stateservice.GetStateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lnrpc.Stateservice.GetStateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static lnrpc.Stateservice.GetStateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lnrpc.Stateservice.GetStateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lnrpc.Stateservice.GetStateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lnrpc.Stateservice.GetStateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static lnrpc.Stateservice.GetStateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lnrpc.Stateservice.GetStateResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lnrpc.GetStateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lnrpc.GetStateResponse)
        lnrpc.Stateservice.GetStateResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lnrpc.Stateservice.internal_static_lnrpc_GetStateResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lnrpc.Stateservice.internal_static_lnrpc_GetStateResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lnrpc.Stateservice.GetStateResponse.class, lnrpc.Stateservice.GetStateResponse.Builder.class);
      }

      // Construct using lnrpc.Stateservice.GetStateResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        state_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lnrpc.Stateservice.internal_static_lnrpc_GetStateResponse_descriptor;
      }

      @java.lang.Override
      public lnrpc.Stateservice.GetStateResponse getDefaultInstanceForType() {
        return lnrpc.Stateservice.GetStateResponse.getDefaultInstance();
      }

      @java.lang.Override
      public lnrpc.Stateservice.GetStateResponse build() {
        lnrpc.Stateservice.GetStateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lnrpc.Stateservice.GetStateResponse buildPartial() {
        lnrpc.Stateservice.GetStateResponse result = new lnrpc.Stateservice.GetStateResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lnrpc.Stateservice.GetStateResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.state_ = state_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lnrpc.Stateservice.GetStateResponse) {
          return mergeFrom((lnrpc.Stateservice.GetStateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lnrpc.Stateservice.GetStateResponse other) {
        if (other == lnrpc.Stateservice.GetStateResponse.getDefaultInstance()) return this;
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                state_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int state_ = 0;
      /**
       * <code>.lnrpc.WalletState state = 1;</code>
       * @return The enum numeric value on the wire for state.
       */
      @java.lang.Override public int getStateValue() {
        return state_;
      }
      /**
       * <code>.lnrpc.WalletState state = 1;</code>
       * @param value The enum numeric value on the wire for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateValue(int value) {
        state_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.lnrpc.WalletState state = 1;</code>
       * @return The state.
       */
      @java.lang.Override
      public lnrpc.Stateservice.WalletState getState() {
        lnrpc.Stateservice.WalletState result = lnrpc.Stateservice.WalletState.forNumber(state_);
        return result == null ? lnrpc.Stateservice.WalletState.UNRECOGNIZED : result;
      }
      /**
       * <code>.lnrpc.WalletState state = 1;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(lnrpc.Stateservice.WalletState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.lnrpc.WalletState state = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lnrpc.GetStateResponse)
    }

    // @@protoc_insertion_point(class_scope:lnrpc.GetStateResponse)
    private static final lnrpc.Stateservice.GetStateResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lnrpc.Stateservice.GetStateResponse();
    }

    public static lnrpc.Stateservice.GetStateResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetStateResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetStateResponse>() {
      @java.lang.Override
      public GetStateResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetStateResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetStateResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lnrpc.Stateservice.GetStateResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SubscribeStateRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SubscribeStateRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SubscribeStateResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SubscribeStateResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_GetStateRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_GetStateRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_GetStateResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_GetStateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022stateservice.proto\022\005lnrpc\"\027\n\025Subscribe" +
      "StateRequest\";\n\026SubscribeStateResponse\022!" +
      "\n\005state\030\001 \001(\0162\022.lnrpc.WalletState\"\021\n\017Get" +
      "StateRequest\"5\n\020GetStateResponse\022!\n\005stat" +
      "e\030\001 \001(\0162\022.lnrpc.WalletState*s\n\013WalletSta" +
      "te\022\020\n\014NON_EXISTING\020\000\022\n\n\006LOCKED\020\001\022\014\n\010UNLO" +
      "CKED\020\002\022\016\n\nRPC_ACTIVE\020\003\022\021\n\rSERVER_ACTIVE\020" +
      "\004\022\025\n\020WAITING_TO_START\020\377\0012\225\001\n\005State\022O\n\016Su" +
      "bscribeState\022\034.lnrpc.SubscribeStateReque" +
      "st\032\035.lnrpc.SubscribeStateResponse0\001\022;\n\010G" +
      "etState\022\026.lnrpc.GetStateRequest\032\027.lnrpc." +
      "GetStateResponseB\'Z%github.com/lightning" +
      "network/lnd/lnrpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_lnrpc_SubscribeStateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lnrpc_SubscribeStateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SubscribeStateRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_SubscribeStateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lnrpc_SubscribeStateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SubscribeStateResponse_descriptor,
        new java.lang.String[] { "State", });
    internal_static_lnrpc_GetStateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lnrpc_GetStateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_GetStateRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_GetStateResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_lnrpc_GetStateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_GetStateResponse_descriptor,
        new java.lang.String[] { "State", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
